version: '3.5'

services:

  elb:
    image: bostonuniversity/elb-simulator:latest
    ports: "443:443"
    environment:
      - REMOTE_URL: "http://webserver"
    depends_on:
      - webserver
    networks:
      - frontend

  webserver:
    image: ghcr.io/ucfopen/materia:webserver-v9.0.1
    platform: linux/amd64
    networks:
      - frontend
      - backend
    depends_on:
      - app
    volumes:
      - public:/var/www/html/public:ro

  app:
    image: ghcr.io/ucfopen/materia:app-v9.0.1
    environment:
      # View Materia README for env settings
      - DATABASE_URL=mysql://materia:odin@host.docker.internal:3306/materia
      - LTI_SECRET=materia-lti-secret
      - SYSTEM_EMAIL=noReply@materia.edu
      - AUTH_SALT=SEE_README
      - AUTH_SIMPLEAUTH_SALT=SEE_README
      - CIPHER_KEY=SEE_README
    volumes:
      - public:/var/www/html/public
      - uploaded_media:/var/www/html/fuel/packages/materia/media
    networks:
      - backend

networks:
  frontend:
    name: materia_frontend
  backend:
    name: materia_backend

volumes:
  uploaded_media: {}
  public: {}
