version: '3.5'

services:

  elb:
    image: bostonuniversity/elb-simulator:latest
    restart: unless-stopped
    ports:
      - "443:443"
    environment:
      - REMOTE_URL=http://webserver # 'webserver' here uses docker-compose's dns alias to the ip of the webserver container below
    depends_on:
      - webserver
    networks:
      - frontend

  webserver:
    image: ghcr.io/ucfopen/materia:webserver-v9.0.1
    restart: unless-stopped
    networks:
      - frontend
      - backend
    depends_on:
      - app
    volumes:
      - public:/var/www/html/public:ro # needed to serve static files from the app container

  app:
    image: ghcr.io/ucfopen/materia:app-v9.0.1
    restart: unless-stopped
    env_file: .env
    volumes:
      - public:/var/www/html/public # needed to provide static js/css files to the webserver
      - uploaded_media:/var/www/html/fuel/packages/materia/media # storage for uploaded media
    networks:
      - backend

  # SUGGEST: In a solid production setup,  this will probably be an external database server
  # If you do use an external server, you'll need to change DATABASE_URL onn the app server
  db:
    image: mysql:5.7.34
    platform: linux/amd64 # needed to get mysql container to run on m1 macs
    restart: unless-stopped
    # ports:
    #   - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=drRoots
      - MYSQL_USER=materia
      - MYSQL_PASSWORD=odin
      - MYSQL_DATABASE=materia
    networks:
      - backend

networks:
  frontend:
    name: materia_frontend
  backend:
    name: materia_backend

volumes:
  uploaded_media: {}
  public: {}
